### ISSUE TITLE
고객 질문

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/gamdonglove#11]
1) 본문 글에 링크 삽입시 링크 미리보기가 가능한가요?
- 링크를 삽입하면 글 썸네일, 제목, 본문을 읽고 박스형태로 나오는 (네이버, 다음 블로그 기능을 상상한 것으로 보임)
- 어렵다고 해도 됩니다. 

2)본문 글 작성 시 한자 쓰기가 불가능 합니다. (쓰면 자동으로 지워짐)
- 법쪽 관련 일을 하시는 조직이라 한자 쓰기 방법 안내는 필요할 듯

**Comment by mozodev** [comment]
1. link preview
https://www.drupal.org/project/opengraph_filter

2. ckeditor 한자 입력 관련 이슈
https://github.com/ckeditor/ckeditor4/issues/676#issuecomment-510845175

**Comment by mozodev** [comment]
빠띠에서도 oembed 추가하는 작업을 했었는데... 링크 미리보기라고 생각하시면 되겠... 
괜찮은 듯한 소개 글 https://meetup.toast.com/posts/81

그때 특이사항은 네이버를 비롯한 한국 웹페이지들이 미리보기가 안되는... 그래서 확인해보니 aws 도쿄리전이라 해외 아이피로 차단당함.. 그래서 국내 서버에 [squid] https://ko.wikipedia.org/wiki/%EC%8A%A4%ED%80%B4%EB%93%9C_(%EC%86%8C%ED%94%84%ED%8A%B8%EC%9B%A8%EC%96%B4) 라는 프록시 서버를 만들어서 성공했던 기억이...
그때도 그냥 이런거 무료로 쓸 수 있는 게 있음 좋겠다 생각했는데.... 뭐 대강 된 듯 ㅎ

![스크린샷 2020-04-23 오전 9 11 56](https://user-images.githubusercontent.com/1661950/80045550-b6d57680-8542-11ea-9208-2d0945c727d0.png)
되긴 되는데 작성화면에서는 이미지가 나오지 않음... ㅎ

**Comment by mozodev** [comment]
2. ckeditor 깃헙 이슈링크를 거니까 해당 이슈에 레퍼런스 찍혔.. 나도 다른 이슈들에 각종 언어별로 된 레퍼런스 보고 아... 정신들없구나 했는데... 이렇게 되는거였...

**Comment by woonjjang** [comment]
1번은 작성화면에 안 나오더라도 적용되면 전달할께요. 
2번은  Drupal CKeditor with IE 11，windows 10 에서는 아직 해결이 안 되어서 불가능 하다는 거죠 ?

**Comment by mozodev** [comment]
ckeditor 레포 이슈에 있는 패치를 해보면 해결할 수도 있습니다.
