### ISSUE TITLE
[디자인 개선] 소개 이해 4개 페이지

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/gamdonglove#12]
http://gamdonglove.durumi.io/about

**Comment by mozodev** [comment]
요건 원고랑 이미지가 완료된거죠? 빈번하게 고칠게 아니라면 그냥 템플릿으로 직접 코드쓰면 빠른데...
그냥 드루팔에서 수정할 수 있는 형태로 갈까요?

**Comment by woonjjang** [comment]
@mozodev 드루팔에서 수정할 수 있는 형태가 좋을 것 같습니다. 
미션, 비전 부분을 스타일링 하며 좋을 듯 한데, 우선 기존에 작업한 부분에 대해서 큰 이슈 없다고 고객이 피드백 준 적이 있습니다.

**Comment by woonjjang** [comment]
*감사와 동행
- 찾아오는 길 중 지도에 단체주소가 표시되도록 해주세요.

**Comment by mozodev** [comment]
http://gamdonglove.durumi.io/contacts
