### ISSUE TITLE
[후원] 후원 등록 및 확인

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/gamdonglove#13]
[이슈]
- 후원 안내 페이지
- 온라인 후원 페이지에서 개인 정보 및 후원 정보를 입력
-  온라인 후원 등록 -> 사인 -> 저장한 페이지를 내부에서 출력할 수 있는 기능

[목업]
- 후원 소개 : https://app.moqups.com/JBF6j8eHpx/view/page/aabf953dd
- 후원 완료 되어 내부에서 출력하는 페이지 : https://app.moqups.com/JBF6j8eHpx/view/page/a96564e4e
- 현재 완료된 후원 문서 모양은 링크와 같음(링크 후원약정서) : https://drive.google.com/drive/u/2/folders/1ZBx6YN9sEs8iqbBMszjygEmaalm1ASoM

**Comment by mozodev** [comment]
일단 이런 개인정보를 받으려면 ssl 사용해야하고...디비 저장 시 암호화도 해야겠네요.
드루팔에서 저장해서 출력하게하는 건 구현할 수 있습니다.  (따로 디비를 만들어서 암호화도 생각했...)
그렇지만 이런 정보가 tcg 서버에 저장되는게 맞는지 모르겠습니다.
요건 제 생각에는 일단 약식으로 다운로드해서 업로드하면 담당자 메일로 보내는 정보로...
추후에 제대로 연결하는게 좋을 듯..
프로젝트에서 반복되는 공통 이슈라서 eplabor에서 서비스형으로 구현하고 그걸 붙히는게 안전할 듯 합니다.

**Comment by woonjjang** [comment]
1. 약식 다운로드해서 후원자가 작성해서 업로드하는 것은 처음 논의할 때 제안을 했었어요. 그런데 다들 잘 하지 않는 행동이어서, 후원신청에 어려울 것 같다고 얘기를 나눴습니다. 이 기관은 또 도너스나 MRM 같은 후원을 신청해서 쓸만큼 큰 단위 후원이 아니기도 해서요. 

2. ssl를 붙이고 드루팔에서 저장 출력해서 초반 버전으로 붙여놓는 것은 어떨까요 ?

**Comment by mozodev** [comment]
요약하면 제 의견은 현재는 디비에 저장하지 않고 그냥 담당자 메일로 보낸다.입니다.
이것도 시간이 좀 걸릴 수 있는 가볍지는 않은 작업입니다.

**Comment by woonjjang** [comment]
넵 알겠습니다. ^^

**Comment by mozodev** [comment]
http://gamdonglove.durumi.io/donate 일단 원고만하고 폼은 내일 작업...

**Comment by woonjjang** [comment]
고객과 우선 공유를 했습니다. 우회하는 방식으로 해 보고, 피드백 받아보시죠.

**Comment by woonjjang** [comment]
### 후원하기 부분
- [x] 1. 후원 메뉴 중 약정서 다운로드 가 안됨 
- [x] 2. 후원 신청서 작성 시 필수적으로 작성해야하는 부분을 작성하지 않으면 경고 팝업창이 뜨고 신청 완료가 되지 않게 해주세요.
- [x] 3. 후원자 정보, 예금주 등 각 항목에 모두 필수라는 의미로 각 항목 옆에 " * (색깔있는 별표)" 를 해주세요. 그리고 모든 항목을 기입하지 않은 채 신청버튼 누르면 적지 않은 부분에 커서키가 놓이고 붉은색 테두리로 표시되어 적기 쉽게 해주세요. 
- [x] 4. 개인정보 관련 확인사항 옆에 (필수)라고 넣어주시고 위와 같이 동의를 체크하지 않은 경우 신청완료가 되지 않게 해주세요.

**Comment by mozodev** [comment]
1. 약정서 다운로드
http://gamdonglove.org/?page_id=3528 후원 화면의 약정서 다운로드 링크 구글 드라이브 링크인데 휴지통에 있다는...
https://drive.google.com/open?id=0B1ifSIEqEtZhOUlYWU40QmZOS0E
일단 구글 드라이브에 있는 [감동]후원약정서.doc_수정안.doc 이 파일을 추가.

**Comment by woonjjang** [comment]
후원하기

- [x]  검증부분 감사하다고(피드백)나이드신 분들이 안 쓴 곳이 있으면"필수값이 입력되 있지 않다" 팝업창을 띄워줄 수 있는지 문의함. 

- [x]  서명 지우고 다시 쓰기 기능 넣을 수 있는지 (안 되면 알려주세요.
- [x]  서면 패등에 있는[  ‘이름 정자로 작성해 주세요’ ]텍스트 삭제
- [x]  약정서 다운로드-> 구글 드라이브로 연결 말고 PDF 다운로드로 될 수 있게 수정
[이주민지원공익센터+감동_후원약정서_125x210mm.pdf](https://github.com/team-durumi/gamdonglove/files/5026171/%2B._._125x210mm.pdf)

**Comment by mozodev** [comment]
완료

**Comment by woonjjang** [comment]
아놔 모조님 ㅋㅋ 
작성한 내용에 문제가 있어요. 한 번 더 살펴보고 고쳐주세요! 어르신! 됐나?

**Comment by woonjjang** [comment]
@mozodev 약정서 다운로드-> 구글 드라이브로 연결 말고 PDF 다운로드로 될 수 있게 수정 
>> Safari에서는 잘 다운로드 되는데, 크롬에서 다운로드 하면 zip파일로 다운로드 되요 ~

**Comment by woonjjang** [comment]
@mozodev 
오류 수정 요청(08.11)
- 법률지원, 제도개선, 공익법 활동 글  목록에서 미리보기 내용이 다 동일함
- 후원하기: 서명이 없어서 신청이 완료됨

**Comment by mozodev** [comment]
<img width="930" alt="스크린샷 2020-08-12 오후 12 53 42" src="https://user-images.githubusercontent.com/6022883/89973278-ebf50880-dc9a-11ea-9457-2fe3f4b106ca.png">

> 1. 법률지원, 제도개선, 공익법 활동 글 목록에서 제목 아래 본문 노출하는 영역에 글귀가 모두 동일하게 나오고 있습니다. 
> 2. 법률지원은 오늘 확인했는데, 제목 아래 본문 노출이 없어졌어요. 개별 글의 본문글이 노출되면 됩니다. 

무슨 뜻인지 이해안됨



> 후원하기: 서명이 없어도 신청이 완료됨

서명이 없어도? 겠죠? ㅎ : 맞습니다. 필수처리되어 있는데, 서명없이도 신청이 완료됩니다.

**Comment by woonjjang** [comment]
@mozodev 어제 제대로 답변 못 해 놨어요 ~

**Comment by woonjjang** [comment]
@mozodev 마지막 적용을 서버에서 수정해 주신 것 같아, 소스코드에만 문구변경 요청 적용했습니다. (반영만 해 주시면 됩니다.)
- 텍스트 수정
- 다운로드 링크 그전 수정내용으로만 변경했습니다.

**Comment by mozodev** [comment]
배포 완료~

**Comment by woonjjang** [comment]
감사합니다.
