### ISSUE TITLE
[메인] 글 게시 영역(하단)

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/gamdonglove#14]
[이슈]
- 디자인 Look & Feel 및 중간에 노출되는 사진 / 메세지는 모두 컨펌 / 수정 반영 완료

[글 게시 영역 모양이 완전히 변경되어야 함.]
- 연간보고서 중에 지정된 글 1개만 현재 디자인 있는 형태로 노출(제안)
<img width="340" alt="스크린샷 2020-04-14 오후 3 17 32" src="https://user-images.githubusercontent.com/6022883/79192255-55871680-7e63-11ea-9a14-dce8c0d7995f.png">

[활동& 공지]
- 메인에 노출 옵션 클릭한 글들만 5개씩 메인에 노출
<img width="582" alt="스크린샷 2020-04-14 오후 3 17 50" src="https://user-images.githubusercontent.com/6022883/79192303-6df73100-7e63-11ea-9cb3-953d691e28d1.png">

**Comment by mozodev** [comment]
views block
- [x] views_block:content_recent-annual_report | /references/annual-report | promote_at_front | 1
- [x] views_block:content_recent-actions | type: action | promote_at_front | 5
- [x] views_block:content_recent-notices | type: notice | promote_at_front | 5

**Comment by mozodev** [comment]
![스크린샷 2020-04-17 오후 5 29 02](https://user-images.githubusercontent.com/1661950/79548792-f3cbe400-80d0-11ea-8d0b-510922c31393.png)
그리드로 보면 이런 형태가 더 나을 듯 한데...
그냥 텍스트로 뿌리면 좀 애매해짐

**Comment by woonjjang** [comment]
저도 괜찮아 보입니다.
요렇게 정리해서 설명드려 볼께요.
