### ISSUE TITLE
[콘텐츠 세부] sidebar 노출(공지사항 / 활동 / 자료실)

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/gamdonglove#15]
- 목록에서 나오는 왼쪽 sidebar를 노출해주면 어떨까요 ? (목업에는 있어서 따로 말씀을 안 드렸습니다. )

**Comment by mozodev** [comment]
pathauto 설정은 디비에 들어갔는데 bulk generate를 안했... 방금 완료해서 사이드바가 보입니다.

**Comment by woonjjang** [comment]
@mozodev 요것도 guest 권한일 때 노출이 안 되는 것 같습니다. 요것만 확인해주시면 될 듯

**Comment by mozodev** [comment]
공지사항
http://gamdonglove.durumi.io/notice/4
활동
http://gamdonglove.durumi.io/action/14
자료실
http://gamdonglove.durumi.io/reference/6

로그인하지 않은 상태에서 사이드바 나오는거 확인 완료!
