### ISSUE TITLE
[모바일 navbar] 모바일 메뉴 정리

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/gamdonglove#16]
모바일 nav-bar와 슬라이드 사이가 벌어져 있어서 클릭했더니 모바일 메뉴가 슬라이드에 가려지는 것 같더라구요. 
2뎁스 메뉴까지 펼쳐지는 것 확인 부탁드려요.

<img width="470" alt="스크린샷 2020-04-23 오전 10 19 04" src="https://user-images.githubusercontent.com/6022883/80050655-366a4200-8551-11ea-9f2f-d672da793e86.png">

**Comment by woonjjang** [comment]
(web) 공지사항에 클릭했을 때 상태값이 설정되어 있는 듯 함.(테마 초기 지정)
(모바일) 몇 개 메뉴를 클릭했더니, 테마에서 포함되어있던 전체 메뉴들이 하위에 전체로 노출되는 듯.

<img width="382" alt="스크린샷 2020-04-23 오후 3 18 44" src="https://user-images.githubusercontent.com/6022883/80065992-10a36400-8576-11ea-9de4-a71122b4636b.png">

<img width="488" alt="스크린샷 2020-04-23 오후 3 18 28" src="https://user-images.githubusercontent.com/6022883/80065983-0b461980-8576-11ea-880d-41de8ab4a62c.png">

**Comment by mozodev** [comment]
이건 뭔지 모르겠음

**Comment by woonjjang** [comment]
메뉴 3줄 버튼 누르기 전에 펼쳐져 있는 상태로 보임.
<img width="484" alt="스크린샷 2020-08-06 오후 9 26 49" src="https://user-images.githubusercontent.com/6022883/89531757-b16b1600-d82b-11ea-8ad3-45dcebf6c0d5.png">

**Comment by mozodev** [comment]
완료
