### ISSUE TITLE
[고객요청] 썸네일 없는 게시글 기본 썸네일 노출

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/gamdonglove#17]
글 중에는 썸네일을 넣지 못 하는 경우의 글들이 있다고 해요. 
썸네일 이미지를 추가하지 않은 경우 아래 이미지가 기본 이미지로 외부에 노출되는 곳에 나오면 좋겠습니다. 
고객에게 이미지를 주고 넣으라고 할 수 있는데, 본문에서 또 항상 노출되는것은 별로인 것 같아요.

애뉴얼리포트 이미지는 맞춰서 넣을 예정

<img width="300" alt="gamdong_thumbnail_300_188" src="https://user-images.githubusercontent.com/6022883/80599746-60969500-8a66-11ea-8da8-8d01e7b6832e.png">

**Comment by woonjjang** [comment]
<img width="640" alt="스크린샷 2020-08-05 오후 1 42 54" src="https://user-images.githubusercontent.com/6022883/89372621-9d3af200-d721-11ea-8c28-913228645311.png">
@mozodev 메인 하단영역 노출되는 영역도 기본 썸네일 노출이 필요합니다.

**Comment by mozodev** [comment]
완료

**Comment by woonjjang** [comment]
확인도 완료 !
