### ISSUE TITLE
[오류]활동목록에서 글 10개 넘을경우 페이지네이션 제공 외

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/gamdonglove#24]
[고객 현재 글 이동중]
- 블로그 글은 전부 옮긴듯
- 홈페이지 글을 옮긴다고 함. 
- 일정상 여유는 좀 있음.

[목록에서 글 10개 넘을경우 페이지네이션 제공]
- 글을 많이 넣었는데 페이지네이션이 필요함.
- 글 목록 위에서 아래까지 정렬순서(글 발행순서로 해 달라고함 / 현재 sticky 조건만 붙어있는 것으로 보임)

http://gamdonglove.durumi.io/actions/legal-support
http://gamdonglove.durumi.io/actions/research
http://gamdonglove.durumi.io/actions/campaign

[목록 썸네일]
- 480*300 에 맞춰서 잘려도 되니 목록에서 형태를 유지하길 바람. 
- 사진에 따라서 300보다 더 길게 나오는 경우가 있어서 수정 요청함.
<img width="868" alt="스크린샷 2020-06-24 오전 11 12 15" src="https://user-images.githubusercontent.com/6022883/85490066-136d1480-b60c-11ea-8aff-67cd9056c237.png">

**Comment by woonjjang** [comment]
#24 #17 #16 은 배포 한 번만 해서 적용 확인만하면 될 것 같은데요. @mozodev

**Comment by mozodev** [comment]
http://gamdonglove.durumi.io/actions/campaign
