### ISSUE TITLE
[활동] 목록 view에서 본문 노출 부분이 반복되는 오류

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/gamdonglove#28]
<img width="930" alt="89973278-ebf50880-dc9a-11ea-9457-2fe3f4b106ca" src="https://user-images.githubusercontent.com/6022883/91126063-18b71000-e6de-11ea-96dd-273d878e96a1.png">

**Comment by mozodev** [comment]
http://gamdonglove.durumi.io/actions/campaign
완료
