### ISSUE TITLE
수정사항

### ISSUE THREAD

**Issue by mozodev** [team-durumi/gamdonglove#30]
## 1. 온라인 후원등록

- [x] 1) 필수사항 모두 작성하지 않으면, “작성한 내용에 문제가 있어요. 한 번 더 살펴보고 고쳐주세요!”라는 팝업이 뜨는데 이 팝업창 내용을 “필수사항을 모두 기재하지 않았습니다. 한 번 더 살펴보고 필수사항을 모두 기재해주세요!”로 변경. 
- [x] 2) 예시로 제시되어 있는 부분에 모두 “예)”를 넣어주세요.
- [ ] 3) 이메일을 제대로 적지 않아도 (예컨대, gd123@naver.com 인 경우 gd123@na 까지만 적어도 다음화면으로 바로 넘어갑니다. 이를 이메일 주소 제대로 모두 적은 후 넘어가게 하거나, 또는 직접입력, 네이버, 다음, 지메일 등등 대표적 메일주소를 고를 수 있게 하는 방법으로 수정.
- [ ] 4) 주소도 위3)항과 동일함. 즉, “서울 서초” 까지만 적어도 다음화면으로 넘어감. 우편번호 등록을 하게끔 해서 주소를 정확히 적을 수 있도록 수정요함. 
- [x] 5) 현재는 “서명” 란에 서명하지 않아도 신청가능하므로 서명란에 서명안하면 팝업창 뜨는 것으로 수정 
- [x] 6) “온라인 후원하기” 제목 옆에, “붉은색 *는 필수사항입니다.” 안내문구 넣기.

## 2. 정기후원 창에서, 오프라인 등록방법 앞부분에, 
- [x] 다음 내용을 넣어주세요.

```
♥ 정기후원은 오프라인 또는 온라인 등록을 통해 가능합니다. 
♥ 보내주신 후원금은 센터 내규에 따라 운영비 및 이주민 지원 기금으로 쓰입니다.
♥ 후원금 사용 내역은 매년 초 연간보고서로 발간되며, 본 홈페이지 자료실에도 업로드 됩니다.
♥ 감동은 투명한 기부금 관리 및 기부금 영수증 발급을 위하여 (재)한빛누리와 공동모금시스템 협약을 체결하였습니다.-- 자세한 내용 클릭버튼
```

## 3. 일시후원 창에서,

- [x]  아래 내용 추가

```
♥ 감동은 투명한 기부금 관리 및 기부금 영수증 발급을 위하여 (재)한빛누리와 공동모금시스템 협약을 체결하였습니다.-- 자세한 내용 클릭버튼을 넣어주세요.
```

## 4. https://blog.naver.com/gamdong318 

- [x] 후원하기 화면에 모달 띄우기

위의 블로그 보시면 후원하기 안내 아래 부분에 한빛누리와 협업사업을 체결하는 안내문이 나옵니다. 
이 내용이 홈페이지 후원하기 부분에 없어서 넣어주시길 요청드립니다.
후원하시는 분이 후원 신청 전에 보실 수 있는 방법으로 관련 안내가 홈페이지에 나타났으면 좋겠습니다. 
안내문은 첨부파일을 확인해 주세요.

**Comment by mozodev** [comment]
@woonjjang 4번 - 안내문은 첨부파일을 확인해 주세요. 요 원고만 좀 여기에 붙여주세요

**Comment by woonjjang** [comment]
![한빛누리 안내문](https://user-images.githubusercontent.com/6022883/91823353-0a379e00-ec74-11ea-9f54-85b1dcafea45.jpg)
@mozodev

**Comment by woonjjang** [comment]
@mozodev 3)4) 필드관련은 고객에게 설명했구요. 배포 한 번 부탁드립니다.

**Comment by woonjjang** [comment]
고생하셨습니다.
