### ISSUE TITLE
[슬라이드] 메인 슬라이드

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/gamdonglove#8]
http://gamdonglove.durumi.io/

[메인 슬라이드]
- 관리자쪽 관리영역 추가
- 이미지 / 큰제목 / 작은 제목/ 텍스트 메세지 / 링크 / 버튼 메세지

[이슈]
- Nav-bar 아래로 슬라이드사 시작되는게 좋을 것 같아요. 
- 디자인은 모조님 의견에 많이 따르겠습니다. 

<img width="1244" alt="스크린샷 2020-04-14 오후 2 57 21" src="https://user-images.githubusercontent.com/6022883/79190853-4357a900-7e60-11ea-9240-1276678e11aa.png">

**Comment by mozodev** [comment]
이미지에는 버튼이 두 개인데 그렇게 갈까요?

**Comment by woonjjang** [comment]
버튼은 하나로 가시죠 ~

**Comment by mozodev** [comment]
로그인 하지 않은 경우 js 에러 수정해야 함
```
Uncaught ReferenceError: jQuery is not defined
    at js_5RTAH2s4CMWIRiQxshvxewu_zBDb4XJKtE0J2LqGUHI.js:25
```

**Comment by woonjjang** [comment]
<img width="448" alt="스크린샷 2020-04-23 오전 10 23 53" src="https://user-images.githubusercontent.com/6022883/80049427-d32ae080-854d-11ea-850b-54e068bc0cc9.png">
슬라이드 좌 - 우 에 보이는 button - 마우스 오버전 컬러가 잘 보이면 좋겠습니다.
